on:
    push:
        branches:
            - master
    pull_request: {}

jobs:
    Build:
        name: Build ${{matrix.config.name}} ${{matrix.type}}
        runs-on: ${{matrix.config.os}}
        strategy:
            matrix:
                type: [Debug, Release]
                config:
                    - { name: "Windows MSVC", os: windows-latest, cc: "cl", cxx: "cl" }
                    - { name: "Linux GCC", os: ubuntu-24.04, cc: "gcc", cxx: "g++" }
                    - { name: "MacOS Clang", os: macos-latest, cc: "clang", cxx: "clang++" }

        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: recursive

            - name: Setup Ninja
              uses: ashutoshvarma/setup-ninja@master
              with:
                version: 1.10.0
            
            - name: Build with CMake
              uses: ashutoshvarma/action-cmake-build@master
              with:
                build-dir: ${{github.workspace}}/build
                cc: ${{matrix.config.cc}}
                cxx: ${{matrix.config.cxx}}
                configure-options: -G Ninja
                build-type: ${{matrix.type}}